### ISSUE TITLE
compile Pattern in the background as a val?

### ISSUE THREAD

**Issue by fommil** [propensive/kaleidoscope#1]
one of my main concerns would be performance... can the regex be compiled and assigned to a val on an `object`?

**Comment by propensive** [comment]
They're currently compiled on first use and stored in a cache, so there's a hash lookup still, and synchronzation contention. It would be interesting to compile the patterns at compile time and then generate an AST of the built pattern directly, but I'm not sure it would be worth it.

**Comment by propensive** [comment]
I've just changed the cache to a Java `ConcurrentHashMap`, and the performance has got quite a bit better, not that I ever had any real feel for how fast or slow it was.

It wouldn't be too difficult to switch to name-based extractors too, which should help some more.

**Comment by fommil** [comment]
Why not just save now in a val? No lookup.

**Comment by propensive** [comment]
Where, exactly?

**Comment by fommil** [comment]
in your test, I would propose on the `Tests` object. But I suppose the heuristic to find *where* could get hairy.

Perhaps a simple heuristic would be "a containing object" or "the companion of the containing class or trait". And if such a thing does not exist, then don't cache it.

But... I know well that this is now beyond the power of a macro. So I see your point about a lookup table.

**Comment by propensive** [comment]
There might be other solutions, but supporting separate compilation dictates that they would have to be file-granularity. I'm going to think about it some more, though I think the string hashes are quite cheap anyway. Benchmarks needed, maybe.

I've got a PR for name-based extractors now, though I want to benchmark the differences before merging.

**Comment by fommil** [comment]
How about interning the string keys and using an identity map for the cache? It's unlikely anything could outperform that.

**Comment by propensive** [comment]
My understanding is that the strings are already interned by virtue of being loaded from the classfile, so the additional interning check is just an unnecessary hash lookup which makes everything slower.

I just experimented by writing a macro which put the patterns into a file-global array. The tests run about 10% faster, but at the expense of some horrible macro code which uses the deprecated `enclosingUnit` API. For 10% better performance, and the increase in complexity, it's not worth it. Basically, compared to the actual parsing, it's not significant.
