### ISSUE TITLE
Fails to parse JSL character classes

### ISSUE THREAD

**Issue by cchepelov** [propensive/kaleidoscope#16]
Kaleidoscope's documentation states that the syntax is _exactly as described in the JSL_ with the obvious exception.

The following sample works:
```scala
import kaleidoscope._

"Janvier 2018" match {
  case r"^${mois:String}@([a-zA-Z]+) +${année}@([0-9]{4})$$" =>
    (mois, année)
}
    // ("Janvier", "2018")
```

the following don't:
```scala
"Janvier 2018" match {
  case r"^${mois:String}@([a-zA-Z]+)\\s+${année}@([0-9]{4})$$" =>
    (mois, année)
}
    // MatchError
```

```scala
"Janvier 2018" match {
  case r"^${mois:String}@(\\S+) +${année}@([0-9]{4})$$" =>
    (mois, année)
}
    // MatchError
```

**Comment by propensive** [comment]
You need to use a single backslash. :) Unlike normal strings, interpolated strings have the same escaping semantics as triple-quoted strings. I've updated the documentation - thanks for making me aware of it!

(I also owe you a response to an email, which I haven't forgotten...) ;)

**Comment by cchepelov** [comment]
Whoa!  Indeed, this works

(now the issue is in IDEA, which displays squiggly lines where it should 
not 😉)


Le 23/01/2019 à 12:43, Jon Pretty a écrit :
