### ISSUE TITLE
captures wrong group, sometimes

### ISSUE THREAD

**Issue by propensive** [propensive/kaleidoscope#17]
```
"ab" match { case r"$x@(a(b))" => x }
```
will result in `x = "b"`, not the expected `x = "ab"`.

**Comment by odisseus** [comment]
### What works correctly
`"ab" match { case r"(a$x@(b))" => x } // x = "b"`
`"ab" match { case r"$x@(a$y@(b))" => (x, y) } // x = "ab", y = "b"`

### What doesn't work
`"ab" match { case r"$x@(a(b))" => x } // x = "b", but should be "ab"`
