### ISSUE TITLE
Scala 2.13 release

### ISSUE THREAD

**Issue by m4dc4p** [propensive/kaleidoscope#24]
Would you consider putting a 2.13-compatible release on Maven Central?

**Comment by mathieuancelinserli** [comment]
@propensive I'd love to get a Scala 2.13 release

I'm using kaleidoscope on a big project and I'd love to upgrade scala version ;)

**Comment by propensive** [comment]
It's on my agenda... hopefully no more than a week away!

**Comment by mathieuancelin** [comment]
Awesome !!! thanks @propensive

**Comment by propensive** [comment]
I'm ludicrously optimistic about when I'll find time for things, sometimes. (Sorry.)

Version 0.5.0 is now on Maven Central, though, for Scala 2.12 and 2.13.

**Comment by mathieuancelin** [comment]
that's awesome @propensive. thanks 👍
