### ISSUE TITLE
Values bound in `match` have type Any instead of String

### ISSUE THREAD

**Issue by vasily-kirichenko** [propensive/kaleidoscope#3]
In `val` binding the val is of type `String`, which is great:

![image](https://user-images.githubusercontent.com/873919/37556652-0441fc86-2a0a-11e8-96be-3fbac7479e95.png)

But in `match` vals have type `Any` unless you add type hint:

![image](https://user-images.githubusercontent.com/873919/37556670-42f5ebb8-2a0a-11e8-9fbb-97532d387097.png)

Considering that no type can be used, but `String`, it looks rather illogical to not always generate the vals of type `String`.

**Comment by propensive** [comment]
I think this is an unavoidable consequence of using whitebox macros, unfortunately.

If I remember correctly, the macro needs to generate code which might be a `Tuple2[String, String]`, `Tuple3[String, String, String]` etc, and there's no common supertype of those which I can offer as the return type of the macro (which is what the IDE uses to infer the type) which would allow each of the extractions to be typed as `String`s.

I don't think there's a way to avoid this, so I'll have to close, not-fixed.
